# Site settings
title: 连雨
email: qqbuby@gmail.com
description: 连雨不知春去，一晴方觉夏深。
baseurl: ""
url: "https://lianyu.codefarm.me"
twitter_username: qqbuby
github_username: qqbuby
timezone: Asia/Shanghai

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Pagination
paginate: 10 

excerpt_separator: ""

# Build Command Options
# incremental: true
livereload: true

# Serve Command Options
host: 0.0.0.0

# Permalinks
permalink: /:year/:month/:day/:title/

# Collections
collections:
  essays:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
  ebooks:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
  journals:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
  paper-books:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
